"""Add DeviceData

Revision ID: 536d83279b85
Revises: 69beb86f204f
Create Date: 2025-04-03 17:06:11.518342

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '536d83279b85'
down_revision = '69beb86f204f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devicedata',
    sa.Column('object', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('room', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('device', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('module', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devicedata_id'), 'devicedata', ['id'], unique=False)
    op.alter_column('controllerboard', 'ip',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.alter_column('controllerboard', 'rabbitmq_user',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint('controllerboard_owner_id_fkey', 'controllerboard', type_='foreignkey')
    op.drop_column('controllerboard', 'owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('controllerboard', sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('controllerboard_owner_id_fkey', 'controllerboard', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.alter_column('controllerboard', 'rabbitmq_user',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('controllerboard', 'ip',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.drop_index(op.f('ix_devicedata_id'), table_name='devicedata')
    op.drop_table('devicedata')
    # ### end Alembic commands ###
