"""Add ControllerBoard

Revision ID: 69beb86f204f
Revises: 1a31ce608336
Create Date: 2025-04-01 22:31:56.903247

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '69beb86f204f'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('controllerfilerequest',
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('secret_key', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_controllerfilerequest_id'), 'controllerfilerequest', ['id'], unique=False)
    op.create_table('controllerboard',
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
    sa.Column('rabbitmq_user', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('access_key', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_onupdate=sa.text('now()'), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic')
    )
    op.create_index(op.f('ix_controllerboard_id'), 'controllerboard', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_controllerboard_id'), table_name='controllerboard')
    op.drop_table('controllerboard')
    op.drop_index(op.f('ix_controllerfilerequest_id'), table_name='controllerfilerequest')
    op.drop_table('controllerfilerequest')
    # ### end Alembic commands ###
