"""Add device, state, history  models

Revision ID: 99f7de56040d
Revises: 536d83279b85
Create Date: 2025-04-05 21:20:21.918372

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '99f7de56040d'
down_revision = '536d83279b85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('pin', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('device_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('controller_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['controller_id'], ['controllerboard.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devicehistory',
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('relay_on_count', sa.Integer(), nullable=True),
    sa.Column('relay_off_count', sa.Integer(), nullable=True),
    sa.Column('rfid_success_count', sa.Integer(), nullable=True),
    sa.Column('rfid_fail_count', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('devicestate',
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('trigger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('trigger_device', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parameter', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('condition', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_controllerboard_id', table_name='controllerboard')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_controllerboard_id', 'controllerboard', ['id'], unique=False)
    op.drop_table('trigger')
    op.drop_table('devicestate')
    op.drop_table('devicehistory')
    op.drop_table('device')
    # ### end Alembic commands ###
