"""Add board and device_state model

Revision ID: bf0f865ec1de
Revises: ce616cb4e2d4
Create Date: 2025-03-30 21:33:41.269724

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bf0f865ec1de'
down_revision = 'ce616cb4e2d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board',
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
    sa.Column('rabbitmq_user', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('access_key', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic')
    )
    op.create_index(op.f('ix_board_id'), 'board', ['id'], unique=False)
    op.create_table('devicestate',
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['board.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devicestate_id'), 'devicestate', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devicestate_id'), table_name='devicestate')
    op.drop_table('devicestate')
    op.drop_index(op.f('ix_board_id'), table_name='board')
    op.drop_table('board')
    # ### end Alembic commands ###
