"""Add iot tables

Revision ID: c1bdc144f204
Revises: 1a31ce608336
Create Date: 2025-04-12 22:27:32.916285

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c1bdc144f204'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('controllerboard',
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=True),
    sa.Column('rabbitmq_user', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('access_key', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic')
    )
    op.create_table('controllerfilerequest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('secret_key', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devicedata',
    sa.Column('object', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('room', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('device', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('module', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devicedata_id'), 'devicedata', ['id'], unique=False)
    op.create_table('device',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('extra_name', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('pin', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('device_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('controller_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['controller_id'], ['controllerboard.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devicehistory',
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hour', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('devicestate',
    sa.Column('parameter', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('trigger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('trigger_device', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parameter', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('condition', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trigger')
    op.drop_table('devicestate')
    op.drop_table('devicehistory')
    op.drop_table('device')
    op.drop_index(op.f('ix_devicedata_id'), table_name='devicedata')
    op.drop_table('devicedata')
    op.drop_table('controllerfilerequest')
    op.drop_table('controllerboard')
    # ### end Alembic commands ###
