"""Add DeviceData model

Revision ID: d37884240597
Revises: 1a31ce608336
Create Date: 2025-03-26 12:50:25.435066

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd37884240597'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devicedata',
    sa.Column('object', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('room', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('device', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('module', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devicedata_id'), 'devicedata', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devicedata_id'), table_name='devicedata')
    op.drop_table('devicedata')
    # ### end Alembic commands ###
